### PR TITLE
Merging feature/display-dependent-modules

### PR DESCRIPTION
**Pull request by tpiekarski**
## Description
- Added two new key-bindings `d` and `alt-d`
- Showing dependent modules within present module information widget
- Cutting content `used by` column at the moment at a fixed width (see following comment)
- Updated documentation README.md, In-app help and manual page to mention how to display dependent modules

## Motivation and Context
Resolves issue #11, Displaying dependent modules

## How Has This Been Tested?
- Checked with multiple selected modules by displaying dependent modules with both keybindings.

## Screenshots / Output (if appropriate):
Screenshot from 2020-04-24 13-13-54

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (no code change)
- [ ] Refactor (refactoring production code)
- [ ] Other 

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have updated the [documentation](https://github.com/orhun/kmon/blob/master/README.md) and [changelog](https://github.com/orhun/kmon/blob/master/CHANGELOG.md) accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] [Rustfmt](https://github.com/rust-lang/rustfmt) and [Rust-clippy](https://github.com/rust-lang/rust-clippy) passed.

### CODE REVIEW

**Comment by tpiekarski** [comment]
## Loose ends

1. Appending `...` turned out to be hard and to be frank I don't understand how this table is generated with tui. At the moment that cutting is happening at a fixed width. 

**Do you know or have an idea about how we could get this available width?**
We could also create an issue over there at tui, because I think such feature could come in handy in rendering tables with tui in general.

2. The column *Used by* contains strings like this `3 foo,bar,baz`
   For being able to cut the prefixed amount of modules two new crates have been added.
    - *regex* for using a pattern like `^\d+\s` to remove `3 `, `11 `, etc.
    - *lazy_static* for having this pattern as a constant

**What do you think? Having plenty of dependencies is not such a good thing. Do you think those will be used in future features?**
  I thought about a possible alternative. See inline todo.

- Counting the commas in this string it could be determine to cut either 1,2, etc. decimals at the beginning + 1 for whitespace
- Reduce external dependencies to only *regex* and drop that (good?) practice of having a constant for the regexp pattern.
- Split this information in two fields when parsing kernel modules from '/proc/modules' or check another source for this information

3. When keybindings for showing dependent modules is pressed multiple times the function show_dependent_modules() is run multiple times. The title `module-name (Dependent modules)` get stacked like this `module-name (Dependent modules) (Dependent modules) (...`
There is a workaround, but I do not like it. Thats what I meant having a toggling function. 

**What do you think about this issue, the workaround and how it could be prevented that this function is run multiple times**
(show_help_message() is running multiple times as well and I think most functions do run like this).

4. Something is odd with dependent modules, not all are available and sometimes there are any listed at all. I'll check further whats going on there.

**Comment by tpiekarski** [comment]
Ahh, one more thing, could we add .vscode to .gitignore? :blush:

**Comment by orhun** [comment]
Here's my changes on top of your code: https://github.com/orhun/kmon/compare/pr14
I haven't tested all the cases but it basically solves most of the issues you referred.

> Something is odd with dependent modules, not all are available and sometimes there are any listed at all. I'll check further whats going on there.

Yeah, maybe [this](https://stackoverflow.com/questions/4073152/how-to-get-complete-dependency-list-of-kernel-modules-at-runtime) would help.

> Do you have some idea how this could be tested?

I'll look into that.

Waiting your feedback on [pr14](https://github.com/orhun/kmon/tree/pr14) branch :blush:

**Comment by tpiekarski** [comment]
> Here's my changes on top of your code: https://github.com/orhun/kmon/compare/pr14
> I haven't tested all the cases but it basically solves most of the issues you referred.

Great, it looks good. I put a [few questions](https://github.com/orhun/kmon/commit/1b410f2ea6b24a146423e543c3fc412587ce15da), especially about the [way how those dependent_width](https://github.com/orhun/kmon/commit/1b410f2ea6b24a146423e543c3fc412587ce15da#r38764910) is calculated. 

One thing is puzzling me, how did you avoid those stacking titles when `show_dependent_modules()` is run multiple times? `kernel_modules.current_name` is referencing itself, is there some hidden mutability/immutability at work?

> > Something is odd with dependent modules, not all are available and sometimes there are any listed at all. I'll check further whats going on there.
> Yeah, maybe [this](https://stackoverflow.com/questions/4073152/how-to-get-complete-dependency-list-of-kernel-modules-at-runtime) would help.

Thanks for the link, I am going to check that.

> > Do you have some idea how this could be tested?
> I'll look into that.

Looking forward for those tests :)

**Comment by tpiekarski** [comment]
> > Here's my changes on top of your code: https://github.com/orhun/kmon/compare/pr14
> > I haven't tested all the cases but it basically solves most of the issues you referred.
> One thing is puzzling me, how did you avoid those stacking titles when `show_dependent_modules()` is run multiple times? `kernel_modules.current_name` is referencing itself, is there some hidden mutability/immutability at work?

Well nevermind, got it... It's that **!** at the beginning of the string. 
Unusual feature, not such a fan of a part of the formatting string which can have impact on logic.
But guess it's a common thing in rust, got to take a closer look at format! macro.

**Comment by tpiekarski** [comment]
> Ahh, one more thing, could we add .vscode to .gitignore?

Commited an update to the .gitignore. Maybe we could include more such files which can not be ignored by .gitignore_global. But for the moment it'll work :)

**Comment by orhun** [comment]
> Division by two because of constraint of 50%?

Yup.

> Is 7 the width of preceding row? When yes, is that value constant?

It's actually the offset value of the 3rd column (`Used by`). It's a constant value as longs as table column count doesn't change. But I have to admit that it's kind of a experimental value which is probably about the table padding. I've seen similar constant values in the tui-rs source so that's why I assume it's about that.

> What does this saturating_sub is doing?

It's basically doing [checked_sub](https://rust-num.github.io/num/num/trait.CheckedSub.html)`.unwrap_or(0)`. It's there just to prevent the underflow and use "0" for the `dependent_width` if the subtraction value is `None`.

> Could modulo be used to make the division clean?

Yeah, that could be used as well. But both of the solutions should be tested further to decide.

> One thing is puzzling me, how did you avoid those stacking titles?

You're right about the "!" but it's actually [here](https://github.com/orhun/kmon/blob/master/src/kernel/cmd.rs#L28).

**Comment by orhun** [comment]
Is there anything else left that you want to add to this pull request? I think it's OK but wanted to ask.

**Comment by tpiekarski** [comment]
Thanks for asking and explaining earlier my loose ends. There is still this issue that not all dependent modules are shown. But it seems that kernel is not tracking those in such a detail that I have expected. No, I don't have anything left to add to this PR.

**Pull request merged**
