### PR TITLE
Creating new sorting argument for most-used modules, resolves #7

### LINKED ISSUE #7: Introduce new sorting argument for most-used module
**Is your feature request related to a problem? Please describe.**
Not a problem, but rather an idea. Its about to quickly identify within kmon the most dependent modules which uses most other modules.

**Describe the solution you'd like**
Passing a new command line argument for sorting. Something like:
`kmon sort -d | --dependents` or `kmon sort -u | --used` 
This argument would sort by the column *used by* at /proc/modules (3rd column) and could also be reversed with `-r`.

What do you think? I'd like to provide a PR as well.

**Describe alternatives you've considered**
None. Such sorting is already present for module name and size.

**Additional context**
None.

### PR DESCRIPTION
**Pull request by tpiekarski**
For details see issue *Introduce new sorting argument for most-used module #7*.

### CODE REVIEW

**Comment by tpiekarski** [comment]
Running clippy gave me plenty of formatting errors. 
Do you have anything additionally configured? 
How to proceed with those errors, or can we ignore them?

**Verbose log running clippy**
`cargo clippy --verbose -- -D warnings 2`
```
       Fresh unicode-xid v0.2.0
       Fresh cfg-if v0.1.10
       Fresh cc v1.0.50
       Fresh autocfg v1.0.0
       Fresh unicode-width v0.1.7
       Fresh numtoa v0.1.0
       Fresh either v1.5.3
       Fresh rustc-demangle v0.1.16
       Fresh vec_map v0.8.1
       Fresh unicode-segmentation v1.6.0
       Fresh ansi_term v0.11.0
       Fresh cassowary v0.3.0
       Fresh strsim v0.8.0
       Fresh colorsys v0.5.3
       Fresh bytesize v1.0.0
       Fresh textwrap v0.11.0
       Fresh itertools v0.8.2
       Fresh proc-macro2 v1.0.10
       Fresh libc v0.2.68
       Fresh log v0.4.8
       Fresh bitflags v1.2.1
       Fresh quote v1.0.3
       Fresh termion v1.5.5
       Fresh atty v0.2.14
       Fresh syn v1.0.17
       Fresh backtrace-sys v0.1.35
       Fresh num-traits v0.2.11
       Fresh enum-iterator-derive v0.5.0
       Fresh synstructure v0.12.3
       Fresh tui v0.8.0
       Fresh clap v2.33.0
       Fresh xcb v0.8.2
       Fresh backtrace v0.3.46
       Fresh enum-iterator v0.5.0
       Fresh x11-clipboard v0.3.3
       Fresh failure_derive v0.1.7
       Fresh enum-unitary v0.4.1
       Fresh clipboard v0.5.0
       Fresh failure v0.1.7
    Checking kmon v1.1.0 (/home/todde/github/kmon)
     Running `/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/clippy-driver rustc --crate-name kmon --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,metadata -C debuginfo=2 -C metadata=6acb517f05f6b0c0 -C extra-filename=-6acb517f05f6b0c0 --out-dir /home/todde/github/kmon/target/debug/deps -C incremental=/home/todde/github/kmon/target/debug/incremental -L dependency=/home/todde/github/kmon/target/debug/deps --extern bytesize=/home/todde/github/kmon/target/debug/deps/libbytesize-f4843cf1452358c2.rmeta --extern clap=/home/todde/github/kmon/target/debug/deps/libclap-4c73036a23341683.rmeta --extern clipboard=/home/todde/github/kmon/target/debug/deps/libclipboard-413588961057b186.rmeta --extern colorsys=/home/todde/github/kmon/target/debug/deps/libcolorsys-9370a770991b7872.rmeta --extern enum_iterator=/home/todde/github/kmon/target/debug/deps/libenum_iterator-1c151643dba6009d.rmeta --extern enum_unitary=/home/todde/github/kmon/target/debug/deps/libenum_unitary-6f273e6d4b450abc.rmeta --extern failure=/home/todde/github/kmon/target/debug/deps/libfailure-4015872c99f0a54c.rmeta --extern termion=/home/todde/github/kmon/target/debug/deps/libtermion-00a989954f2c9516.rmeta --extern tui=/home/todde/github/kmon/target/debug/deps/libtui-63f1248d60e19978.rmeta --extern unicode_width=/home/todde/github/kmon/target/debug/deps/libunicode_width-e688f59360df739e.rmeta -L native=/home/todde/github/kmon/target/debug/build/backtrace-sys-ddb34e463ec9a366/out`
error: using tabs in doc comments is not recommended
  --> src/app.rs:38:1
   |
38 |      * Return iterator of the available scroll directions.
   | ^^^^ help: consider using four spaces per tab
   |
   = note: `-D clippy::tabs-in-doc-comments` implied by `-D warnings`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#tabs_in_doc_comments

[... other 193 errors of same type but different files and locations...]

error: aborting due to 194 previous errors

error: could not compile `kmon`.

Caused by:
  process didn't exit successfully: `/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/clippy-driver rustc --crate-name kmon --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,metadata -C debuginfo=2 -C metadata=6acb517f05f6b0c0 -C extra-filename=-6acb517f05f6b0c0 --out-dir /home/todde/github/kmon/target/debug/deps -C incremental=/home/todde/github/kmon/target/debug/incremental -L dependency=/home/todde/github/kmon/target/debug/deps --extern bytesize=/home/todde/github/kmon/target/debug/deps/libbytesize-f4843cf1452358c2.rmeta --extern clap=/home/todde/github/kmon/target/debug/deps/libclap-4c73036a23341683.rmeta --extern clipboard=/home/todde/github/kmon/target/debug/deps/libclipboard-413588961057b186.rmeta --extern colorsys=/home/todde/github/kmon/target/debug/deps/libcolorsys-9370a770991b7872.rmeta --extern enum_iterator=/home/todde/github/kmon/target/debug/deps/libenum_iterator-1c151643dba6009d.rmeta --extern enum_unitary=/home/todde/github/kmon/target/debug/deps/libenum_unitary-6f273e6d4b450abc.rmeta --extern failure=/home/todde/github/kmon/target/debug/deps/libfailure-4015872c99f0a54c.rmeta --extern termion=/home/todde/github/kmon/target/debug/deps/libtermion-00a989954f2c9516.rmeta --extern tui=/home/todde/github/kmon/target/debug/deps/libtui-63f1248d60e19978.rmeta --extern unicode_width=/home/todde/github/kmon/target/debug/deps/libunicode_width-e688f59360df739e.rmeta -L native=/home/todde/github/kmon/target/debug/build/backtrace-sys-ddb34e463ec9a366/out` (exit code: 1)

```

**Comment by tpiekarski** [comment]
Btw how do you create those gifs? Can you update the gif showing the sorting?

**Comment by tpiekarski** [comment]
> Running clippy gave me plenty of formatting errors.
> Do you have anything additionally configured?
> How to proceed with those errors, most of those files wasn't touched, or can we ignore them?
> 
> **Verbose log running clippy**
> `cargo clippy --verbose -- -D warnings 2`
> 
> ```
>        Fresh unicode-xid v0.2.0
>        Fresh cfg-if v0.1.10
>        Fresh cc v1.0.50
>        Fresh autocfg v1.0.0
>        ....
> ```

Okay, `-A clippy::tabs-in-doc-comments` does the trick.
Do you update the CHANGELOG.md upon review and merge or should it go already into this PR?
Where do you set the docker tags, docker failing with `Error parsing reference: "/kmon:latest" is not a valid repository/tag: invalid reference format`

**Comment by orhun** [comment]
I use [peek](https://github.com/phw/peek) for recording GIFs. I'll update the README.md and CHANGELOG.md after merging this PR. Docker tags are set in [CI](https://github.com/orhun/kmon/blob/master/.github/workflows/ci.yml#L86) workflow.

**Comment by orhun** [comment]
Okay I've just tested it. Works pretty well. 
But there was one thing that bothered me: `-u`
It might cause conflicts since there's already an `-u` flag for showing the Unicode characters. It's a flag for subcommand, but still, it might be changed to something else like `-d, --dependent`.
But then I've realized that the following text is so symmetric:

```
kmon sort --name
kmon sort --size
kmon sort --used
```

Something like `-d, --deps` can be used for keeping it symmetric but `deps` is not meaningful enough. Looks like I will sacrifice clarity for symmetry.

Maybe the description of the flag can be changed to `Sort modules by their dependent modules`.
Other than that, it looks great!

**Comment by orhun** [comment]
And uh... what happened to the PR template? 😅

**Comment by tpiekarski** [comment]
> [...] I'll update the README.md and CHANGELOG.md after merging this PR. Docker tags are set in [CI](https://github.com/orhun/kmon/blob/master/.github/workflows/ci.yml#L86) workflow.

Should the version in Cargo.toml increased also after the PR have been merged?
I already increased it, maybe that's the reason why docker fails.

> And uh... what happened to the PR template?

Ups... :innocent: :blush: 

> [...]
> It might cause conflicts since there's already an `-u` flag for showing the Unicode characters. It's a flag for subcommand, but still, it might be changed to something else like `-d, --dependent`.
> [...]
> Maybe the description of the flag can be changed to `Sort modules by their dependent modules`.
> Other than that, it looks great!

Thanks, I'm going to go for `-d, --dependent`, reword the description as well and change PR
(that symmetry also looked intriguing to me, but... :man_shrugging:).

**Pull request merged**
